### ISSUE TITLE
Some não funciona como o esperado

### ISSUE THREAD

**Issue by paulo70** [lfrprazeres/react-context#2]
https://github.com/lfrprazeres/react-context/blob/a1797c1c6fe386f9d9132696a943f5dc77423ff5/src/common/contexts/Carrinho.js#L51

Instrutor, a verificação **some()** para ver se existe algum id dentro do array que seja igual ao novo id adicionado, não funciona.
Primeiro dever se colocar uma interrogação ? para verificar se o cart está vazio, ok. Tirando isso já temos um erro.
**const handleAddProducts = (newItem)** 
ex: **const hasItem = cart?.some(itemCar => itemCar.id === newItem.id)**

Só que o **cart** sempre vem undefined, e com isso ele sempre cai dentro do **if** e não incrementa a quantidade, criando um novo objeto sempre
**if (!hasItem) {
      newItem.count = 1
      return setCart(itemPrev => [...itemPrev, newItem])
    }**
    
    **setCart(itemPrev => itemPrev.map(itemCar => {
      if (itemCar.id === newItem.id) itemCar.count += 1
      return itemCar
    }))**
    
    Consegue ajudar, por favor?

**Comment by lfrprazeres** [comment]
Fala Paulo, beleza?

consegue me enviar o link do seu repositório para que eu consiga reproduzir o erro? A função dentro do some aceita um booleano como retorno, então a forma que está deveria funcionar como esperado.

**Comment by paulo70** [comment]
> Fala Paulo, beleza?
> 
> consegue me enviar o link do seu repositório para que eu consiga reproduzir o erro? A função dentro do some aceita um booleano como retorno, então a forma que está deveria funcionar como esperado.

Ok, Vou te enviar.

**Comment by paulo70** [comment]
https://github.com/paulo70/react-context

**Comment by paulo70** [comment]
@lfrprazeres  Enviei o link. A única coisa que mudei foram os nomes de variáveis

**Comment by paulo70** [comment]
@lfrprazeres arrumei o erro, era o nome da variável errado, que vacilo, foi mal. Muito obrigado!! Não se preocupe

**Comment by lfrprazeres** [comment]
@paulo70 o problema é que dentro do seu context você chamou o seu estado de "car", não "cart", mudando isso funciona normalmente

**Comment by lfrprazeres** [comment]
ah, que bom que achou! sem problemas!

**Comment by paulo70** [comment]
> @paulo70 o problema é que dentro do seu context você chamou o seu estado de "car", não "cart", mudando isso funciona normalmente

@lfrprazeres exatemente hahaha

**Comment by paulo70** [comment]
@lfrprazeres Obrigado mais uma vez pela atenção

**Comment by paulo70** [comment]
> https://github.com/lfrprazeres/react-context/blob/a1797c1c6fe386f9d9132696a943f5dc77423ff5/src/common/contexts/Carrinho.js#L51
> 
> Instrutor, a verificação **some()** para ver se existe algum id dentro do array que seja igual ao novo id adicionado, não funciona. Primeiro dever se colocar uma interrogação ? para verificar se o cart está vazio, ok. Tirando isso já temos um erro. **const handleAddProducts = (newItem)** ex: **const hasItem = cart?.some(itemCar => itemCar.id === newItem.id)**
> 
> Só que o **cart** sempre vem undefined, e com isso ele sempre cai dentro do **if** e não incrementa a quantidade, criando um novo objeto sempre **if (!hasItem) { newItem.count = 1 return setCart(itemPrev => [...itemPrev, newItem]) }**
> 
> ```
> **setCart(itemPrev => itemPrev.map(itemCar => {
>   if (itemCar.id === newItem.id) itemCar.count += 1
>   return itemCar
> }))**
> 
> Consegue ajudar, por favor?
> ```
